"""empty message

Revision ID: 06165713417e
Revises: 3d33fc104a6d
Create Date: 2022-12-22 20:21:22.954350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06165713417e'
down_revision = '3d33fc104a6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_unique_constraint(None, ['phone'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###