"""empty message

Revision ID: 3d33fc104a6d
Revises: 2a12e6dbcebe
Create Date: 2022-12-22 19:52:49.121779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d33fc104a6d'
down_revision = '2a12e6dbcebe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint('employees_email_key', type_='unique')
        batch_op.drop_constraint('employees_phone_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.create_unique_constraint('employees_phone_key', ['phone'])
        batch_op.create_unique_constraint('employees_email_key', ['email'])

    # ### end Alembic commands ###