"""empty message

Revision ID: 4b0c7edcecf0
Revises: bd12cad54c41
Create Date: 2022-12-20 22:05:37.481057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b0c7edcecf0'
down_revision = 'bd12cad54c41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('birthday', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['phone'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('birthday')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###