"""empty message

Revision ID: ff8ea63de96b
Revises: 4b0c7edcecf0
Create Date: 2022-12-21 23:47:15.081482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff8ea63de96b'
down_revision = '4b0c7edcecf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint('employees_company_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'company', ['company_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('employees_company_id_fkey', 'company', ['company_id'], ['id'])

    # ### end Alembic commands ###