version: '3'

services:
    web:
        build:
            dockerfile: ./docker/python/Dockerfile
            context: ./ #щоб докерфайл вважав що він знаходиться в flask intro
        ports:
            - "5000:5000"
        volumes:
            - .:/code
